services:
  flashcards-ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ai:/app
    networks:
      - flashcards-network

  flashcards-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - flashcards-network

networks:
  flashcards-network:
    driver: bridge

volumes:
  flashcards-ai:
    driver: local