line-length = 88

target-version = "py313"

[lint]
select = [
    "E",
    "F",
    "I",
    "B",
]
ignore = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"