# Generated by Django 5.2.3 on 2025-06-16 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='condition',
            field=models.CharField(choices=[
                ('first_deck', 'Erstes Deck erstellt'),
                ('first_review', 'Erste Karte bewertet'),
                ('perfect_session', 'Perfekte Lernsession'),
                ('deck_master', 'Deck-Meister'),
                ('review_streak', 'Lernstreak'),
            ], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='status',
            field=models.CharField(choices=[
                ('active', 'Aktiv'),
                ('completed', 'Abgeschlossen'),
                ('abandoned', 'Abgebrochen'),
            ], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('theme', models.CharField(choices=[
                    ('light', 'Hell'),
                    ('dark', 'Dunkel'),
                    ('system', 'System'),
                ], default='system', max_length=255)),
                ('font_size', models.CharField(choices=[
                    ('small', 'Klein'),
                    ('medium', 'Mittel'),
                    ('large', 'Groß'),
                ], default='medium', max_length=255)),
                ('privacy_settings', models.CharField(choices=[
                    ('show_stats', 'Stats anzeigen'),
                    ('show_decks', 'Decks anzeigen'),
                    ('show_progress', 'Fortschritt anzeigen'),
                ], default='show_stats', max_length=255)),
                ('notification_settings', models.CharField(choices=[
                    ('email_notifications', 'E-Mail-Benachrichtigungen'),
                    ('learning_reminders', 'Lern-Erinnerungen'),
                    ('achievement_alerts', 'Erfolgsbenachrichtigungen'),
                ], default='email_notifications', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='settings',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'verbose_name': 'Einstellungen',
                'verbose_name_plural': 'Einstellungen',
                'ordering': ['-updated_at'],
            },
        ),
    ]
