# Generated by Django 5.2.3 on 2025-06-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Ob das Profil öffentlich sichtbar ist'),
        ),
    ]
