# Generated by Django 5.2.3 on 2025-06-17 13:32

import cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_user_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profilbild des Benutzers', null=True, upload_to=cards.models.user_avatar_path),
        ),
    ]
